// DON'T EDIT. this code is generated by nene.
use google_cloud_googleapis::spanner::v1::Mutation;

use google_cloud_spanner::client::RunInTxError;
use google_cloud_spanner::key::Key;
use google_cloud_spanner::mutation::{delete, insert_or_update_struct, insert_struct, replace_struct, update_struct};

use google_cloud_spanner::statement::{Statement, ToKind};
use google_cloud_spanner::transaction::CallOptions;
use google_cloud_spanner::transaction::Transaction;

use google_cloud_spanner_derive::Table;

use crate::domain::model::read_by_statement;
use serde::Serialize;
use tracing::instrument;

pub const TABLE_NAME: &str = "User";
pub const COLUMN_USER_ID: &str = "UserId";
pub const COLUMN_PREMIUM: &str = "Premium";
pub const COLUMN_UPDATED_AT: &str = "UpdatedAt";

#[derive(Clone, Debug, Table, Default, Serialize)]
pub struct User {
    pub user_id: String,
    pub premium: bool,
    pub updated_at: chrono::DateTime<chrono::Utc>,
}

impl User {
    pub fn insert(&self) -> Mutation {
        insert_struct(TABLE_NAME, self)
    }

    pub fn update(&self) -> Mutation {
        update_struct(TABLE_NAME, self)
    }

    pub fn replace(&self) -> Mutation {
        replace_struct(TABLE_NAME, self)
    }

    pub fn insert_or_update(&self) -> Mutation {
        insert_or_update_struct(TABLE_NAME, self)
    }

    pub fn delete(&self) -> Mutation {
        delete(TABLE_NAME, Key::new(&self.user_id))
    }

    #[instrument(skip_all)]
    pub async fn find_by_pk(
        tx: &mut Transaction,
        user_id: &String,
        options: Option<CallOptions>,
    ) -> Result<Option<Self>, RunInTxError> {
        let mut stmt = Statement::new("SELECT * From User WHERE UserId = @UserId");
        stmt.add_param(COLUMN_USER_ID, user_id);
        let mut rows = read_by_statement(tx, stmt, options).await?;
        if !rows.is_empty() {
            Ok(rows.pop())
        } else {
            Ok(None)
        }
    }
}
