// DON'T EDIT. this code is generated by nene.
use google_cloud_spanner::row::{Error as RowError, Struct, TryFromStruct, Row};
use google_cloud_spanner::statement::{Kinds, ToKind, ToStruct, Types};
use google_cloud_spanner::mutation::{insert_struct, update_struct, replace_struct, insert_or_update_struct, delete};
use google_cloud_spanner::value::CommitTimestamp;
use google_cloud_spanner::key::Key;
use google_cloud_googleapis::spanner::v1::Mutation;
use std::convert::TryFrom;

pub const TABLE_NAME : &str = "User";
pub const COLUMN_USER_ID : &str = "UserId";
pub const COLUMN_PREMIUM : &str = "Premium";
pub const COLUMN_UPDATED_AT : &str = "UpdatedAt";

pub struct User {
    pub user_id: String,
    pub premium: bool,
    pub updated_at: chrono::DateTime<chrono::Utc>,
}

impl User {
    pub fn insert(&self) -> Mutation {
        insert_struct(TABLE_NAME, &self)
    }

    pub fn update(&self) -> Mutation {
        update_struct(TABLE_NAME, &self)
    }

    pub fn replace(&self) -> Mutation {
        replace_struct(TABLE_NAME, &self)
    }

    pub fn insert_or_update(&self) -> Mutation {
        insert_or_update_struct(TABLE_NAME, &self)
    }

    pub fn delete(&self) -> Mutation {
        delete(TABLE_NAME, Key::key(&self.user_id))
    }
}

impl ToStruct for User {
    fn to_kinds(&self) -> Kinds {
        vec![
            (COLUMN_USER_ID, self.user_id.to_kind()),
            (COLUMN_PREMIUM, self.premium.to_kind()),
            (COLUMN_UPDATED_AT, CommitTimestamp::new().to_kind()),
        ]
    }

    fn get_types() -> Types {
        vec![
            (COLUMN_USER_ID, String::get_type()),
            (COLUMN_PREMIUM, bool::get_type()),
            (COLUMN_UPDATED_AT, CommitTimestamp::get_type()),
        ]
    }
}

impl TryFromStruct for User {
    fn try_from(s: Struct<'_>) -> Result<Self, RowError> {
        Ok(User {
            user_id: s.column_by_name(COLUMN_USER_ID)?,
            premium: s.column_by_name(COLUMN_PREMIUM)?,
            updated_at: s.column_by_name(COLUMN_UPDATED_AT)?,
        })
    }
}

impl TryFrom<Row> for User {
    type Error = RowError;
    fn try_from(row: Row) -> Result<Self, RowError> {
        Ok(User {
            user_id: row.column_by_name(COLUMN_USER_ID)?,
            premium: row.column_by_name(COLUMN_PREMIUM)?,
            updated_at: row.column_by_name(COLUMN_UPDATED_AT)?,
        })
    }
}

