version: "3.8"

services:
  pubsub:
    image: messagebird/gcloud-pubsub-emulator:latest
    ports:
      - "8681:8681"
    environment:
      PUBSUB_PROJECT1: "local-project,chat:chat"
  rust-api:
    build:
      context: rust
    ports:
      - "8091:8091"
    links:
      - pubsub
    environment:
      RUST_LOG: info,google_cloud_pubsub=trace
      PUBSUB_EMULATOR_HOST: pubsub:8681
      PUBSUB_PROJECT: local-project