# Source: api/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rust-ws
  labels:
    name: rust-ws
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: rust-ws
  template:
    metadata:
      labels:
        app: rust-ws
    spec:
      serviceAccountName: example
      containers:
        - name: rust-ws
          securityContext:
            {}
          image: "asia.gcr.io/<your_project>/rust-ws:latest"
          imagePullPolicy: Always
          env:
            - name: PUBSUB_PROJECT
              value: <your_project>
            - name: RUST_LOG
              value: info,google_cloud_pubsub=trace
          ports:
            - name: http
              containerPort: 8091
              protocol: TCP
          resources:
            requests:
              cpu: 2000m
              memory: 2Gi
            limits:
              cpu: 2000m
              memory: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: rust-ws
  labels:
    app: rust-ws
spec:
  type: NodePort
  ports:
    - port: 8091
      targetPort: 8091
      protocol: TCP
      name: rust-ws
  selector:
    app: rust-ws